export const actionTypes = {
    GET_ROOM_BY_ID: "GET_ROOM_BY_ID",
    GET_ROOMS_BY_IDHOUSE: "GET_ROOMS_BY_IDHOUSE",
    CREATE_ROOM: "CREATE_ROOM",
    UPDATE_ROOM: "UPDATE_ROOM",
    DELETE_ROOM: "DELETE_ROOM",
}