export const actionTypes = {
    GET_HOME_BY_ID: "GET_HOME_BY_ID",
    GET_ROOMS_BY_TYPE: "GET_ROOMS_BY_TYPE",
    GET_ALL_CITIES: "GET_ALL_CITIES",
    GET_ALL_HOME: "GET_ALL_HOME",
    GET_HOME_BY_CITY: "GET_HOME_BY_CITY",
    SEARCH_BY_NAME: "SEARCH_BY_NAME",
    CREATE_HOME: "CREATE_HOME",
    DELETE_HOME: "DELETE_HOME",
    UPDATE_HOME: "UPDATE_HOME",
}