export const actionTypes = {
    GET_ALL_CONTRACT: "GET_ALL_CONTRACT",
    GET_CONTRACT_BY_ID: "GET_CONTRACT_BY_ID",
    GET_CONTRACT_BY_USERID: "GET_CONTRACT_BY_USERID",
    UPDATE_CONTRACT_STATUS: "UPDATE_CONTRACT_STATUS",
    CREATE_CONTRACT: "CREATE_CONTRACT",
    UPDATE_CONTRACT: "UPDATE_CONTRACT",
}