export const actionTypes = {
    GET_NOTIFICATION_FOR_USER: "GET_NOTIFICATION_FOR_USER",
    GET_NOTIFICATION_UNREAD_FOR_USER: "GET_NOTIFICATION_UNREAD_FOR_USER",
    MASK_NOTIFICATION_AS_READ: "MASK_NOTIFICATION_AS_READ",
}