export const actionTypes = {
    CREATE_INVOICE: "CREATE_INVOICE",
    CREATE_INVOICE_DETAIL: "CREATE_INVOICE_DETAIL",
    GET_INVOICE_OF_CONTRACT: "GET_INVOICE_OF_CONTRACT",
    UPDATE_DUEDATE_INVOICE: "UPDATE_DUEDATE_INVOICE",
    GET_INVOICE_DETAIL_FOR_INVOICE: "GET_INVOICE_DETAIL_FOR_INVOICE",
    STATISTICAL_BY_YEAR: "STATISTICAL_BY_YEAR",
}