export const actionTypes = {
    GET_ALL_BOOKING: "GET_ALL_BOOKING",
    UPDATE_BOOKING_STATUS: "UPDATE_BOOKING_STATUS",
    GET_BOOKING_BY_STATUS: "GET_BOOKING_BY_STATUS",
    CREATE_BOOKING: "CREATE_BOOKING",
    GET_BOOKING_FOR_USER: "GET_BOOKING_FOR_USER",
}